# Generated by Django 4.2.30 on 2026-04-15 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import permohonan.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permohonan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('diajukan', 'Diajukan'), ('verifikasi', 'Sedang Diverifikasi'), ('diproses', 'Sedang Diproses'), ('perlu_revisi', 'Perlu Revisi'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak')], default='draft', max_length=20)),
                ('nama_anak', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('nik_anak', models.CharField(max_length=16, verbose_name='NIK Anak')),
                ('tempat_lahir', models.CharField(max_length=100, verbose_name='Tempat Lahir')),
                ('tanggal_lahir', models.DateField(verbose_name='Tanggal Lahir')),
                ('nomor_akta', models.CharField(max_length=50, verbose_name='Nomor Akta Kelahiran')),
                ('nama_ayah', models.CharField(max_length=150, verbose_name='Nama Ayah')),
                ('nik_ayah', models.CharField(max_length=16, verbose_name='NIK Ayah')),
                ('no_nikah_ayah', models.CharField(blank=True, max_length=50, null=True, verbose_name='No. Buku Nikah Ayah')),
                ('nama_ibu', models.CharField(max_length=150, verbose_name='Nama Ibu')),
                ('nik_ibu', models.CharField(max_length=16, verbose_name='NIK Ibu')),
                ('no_nikah_ibu', models.CharField(blank=True, max_length=50, null=True, verbose_name='No. Buku Nikah Ibu')),
                ('tanggal_menikah', models.DateField(blank=True, null=True, verbose_name='Tanggal Menikah')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('diajukan_pada', models.DateTimeField(blank=True, null=True)),
                ('pemohon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permohonan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permohonan',
                'verbose_name_plural': 'Permohonan',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_lama', models.CharField(blank=True, choices=[('draft', 'Draft'), ('diajukan', 'Diajukan'), ('verifikasi', 'Sedang Diverifikasi'), ('diproses', 'Sedang Diproses'), ('perlu_revisi', 'Perlu Revisi'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak')], max_length=20)),
                ('status_baru', models.CharField(choices=[('draft', 'Draft'), ('diajukan', 'Diajukan'), ('verifikasi', 'Sedang Diverifikasi'), ('diproses', 'Sedang Diproses'), ('perlu_revisi', 'Perlu Revisi'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak')], max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('permohonan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat', to='permohonan.permohonan')),
            ],
            options={
                'verbose_name': 'Riwayat Status',
                'verbose_name_plural': 'Riwayat Status',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='Berkas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jenis', models.CharField(choices=[('akta_kelahiran', 'Akta Kelahiran'), ('kk', 'Kartu Keluarga'), ('buku_nikah', 'Buku Nikah Orang Tua'), ('ktp_ayah', 'KTP Ayah / Akta Kematian Ayah'), ('ktp_ibu', 'KTP Ibu / Akta Kematian Ibu')], max_length=30)),
                ('file', models.FileField(upload_to=permohonan.models.upload_berkas_path)),
                ('nama_file', models.CharField(max_length=255)),
                ('diunggah_pada', models.DateTimeField(auto_now_add=True)),
                ('permohonan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berkas', to='permohonan.permohonan')),
            ],
            options={
                'verbose_name': 'Berkas',
                'verbose_name_plural': 'Berkas',
                'unique_together': {('permohonan', 'jenis')},
            },
        ),
    ]
