# Generated by Django 4.2.30 on 2026-04-18 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import permohonan.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permohonan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilAkta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=permohonan.models.upload_hasil_path)),
                ('nama_file', models.CharField(max_length=255)),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan untuk pemohon')),
                ('diunggah_pada', models.DateTimeField(auto_now_add=True)),
                ('diunggah_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hasil_diunggah', to=settings.AUTH_USER_MODEL)),
                ('permohonan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_akta', to='permohonan.permohonan')),
            ],
            options={
                'verbose_name': 'Hasil Akta',
                'verbose_name_plural': 'Hasil Akta',
            },
        ),
    ]
